[hypervisor.qemu]
enable_debug = true
shared_fs = "virtio-fs"
virtio_fs_daemon = "/opt/kata/libexec/virtiofsd"
valid_virtio_fs_daemon_paths = ["/opt/kata/libexec/virtiofsd"]
file_mem_backend = "/tmp"

[agent.kata]
enable_debug = true

[runtime]
enable_debug = true
disable_new_netns = true
internetworking_model = "none"
